const SUBSCRIBE_USER = 'SUBSCRIBE_USER';
const CREATE_WORK = 'CREATE_WORK';
const UPDATE_STATUS_WORK = 'UPDATE_STATUS_WORK';
const UPDATE_LOCATION = 'UPDATE_LOCATION';
const GET_LOCATIONS = 'GET_LOCATIONS';
const GET_OFF_LOCATIONS = 'GET_OFF_LOCATIONS';

module.exports = {
    SUBSCRIBE_USER,
    CREATE_WORK,
    UPDATE_STATUS_WORK,
    UPDATE_LOCATION,
    GET_LOCATIONS,
    GET_OFF_LOCATIONS
}